# Generated by Django 5.0.1 on 2024-01-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='suppliers',
            field=models.ManyToManyField(through='inventory_management.SupplierItem', to='inventory_management.supplier'),
        ),
    ]
